[phases.setup]
nixPkgs = ["python311", "git", "curl"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg",
    "echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main' | tee /etc/apt/sources.list.d/github-cli.list",
    "apt update && apt install gh -y || echo 'gh install may need manual setup'"
]

[start]
cmd = "python src/main.py"